# Generated by Django 5.2.7 on 2025-11-11 06:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0002_alter_animal_options_alter_animal_generic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(verbose_name='寄付金額（円）')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='寄付者住所')),
                ('message', models.TextField(blank=True, null=True, verbose_name='応援メッセージ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='寄付日時')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='寄付者')),
                ('zoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.zoo', verbose_name='寄付先の動物園')),
            ],
            options={
                'verbose_name': '寄付',
                'verbose_name_plural': '寄付',
                'db_table': 'donations',
            },
        ),
    ]
