# Generated by Django 5.2.7 on 2025-11-12 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_options_alter_animal_generic_and_more'),
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='メッセージ'),
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ハンコ名')),
                ('image', models.ImageField(upload_to='stamps/', verbose_name='ハンコ画像')),
                ('is_active', models.BooleanField(default=True, verbose_name='使用中')),
                ('zoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.zoo', verbose_name='動物園')),
            ],
            options={
                'unique_together': {('zoo', 'is_active')},
            },
        ),
    ]
