# Generated by Django 5.2.7 on 2025-11-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_donation_message_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='zoo_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='寄付先住所'),
        ),
        migrations.AddField(
            model_name='donation',
            name='zoo_postcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='寄付先郵便番号'),
        ),
    ]
