# Generated by Django 5.2.7 on 2025-11-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_donation_zoo_address_donation_zoo_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='zoo_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='寄付先電話番号'),
        ),
    ]
