# Generated by Django 5.2.7 on 2025-11-17 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0005_animal_diet_animal_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='返礼品タイトル')),
                ('description', models.TextField(blank=True, verbose_name='返礼品説明')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='gift_images/main/', verbose_name='メイン画像')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='animals.zoo', verbose_name='動物園')),
            ],
            options={
                'verbose_name': '返礼品（メイン）',
                'verbose_name_plural': '返礼品（メイン）',
                'db_table': 'gifts',
            },
        ),
        migrations.CreateModel(
            name='GiftImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gift_images/sub/', verbose_name='サブ画像')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='キャプション（説明）')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='表示順')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gift.gift', verbose_name='返礼品')),
            ],
            options={
                'verbose_name': '返礼品追加画像',
                'verbose_name_plural': '返礼品追加画像',
                'db_table': 'gift_images',
                'ordering': ['display_order'],
            },
        ),
    ]
