# Generated by Django 5.2.7 on 2025-11-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='price',
            field=models.IntegerField(default=0, verbose_name='プラン金額'),
        ),
    ]
