# Generated by Django 5.2.7 on 2025-10-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('generic', models.CharField(max_length=100, verbose_name='属')),
                ('specific', models.CharField(max_length=100, verbose_name='種')),
                ('scientific', models.CharField(max_length=200, verbose_name='学名')),
                ('japanese', models.CharField(max_length=100, verbose_name='和名')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('sex', models.CharField(blank=True, choices=[('M', 'オス'), ('F', 'メス'), ('U', '不明')], max_length=1, null=True, verbose_name='性別')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='誕生日')),
                ('txt', models.TextField(verbose_name='説明文')),
                ('pic1', models.ImageField(upload_to='animal_images/', verbose_name='画像1')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='animal_images/', verbose_name='画像2')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='animal_images/', verbose_name='画像3')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='animal_images/', verbose_name='画像4')),
                ('pic5', models.ImageField(blank=True, null=True, upload_to='animal_images/', verbose_name='画像5')),
                ('total_point', models.PositiveIntegerField(default=0, verbose_name='推しポイント')),
            ],
            options={
                'verbose_name': '動物',
                'verbose_name_plural': '動物',
                'db_table': 'animals',
            },
        ),
    ]
