# Generated by Django 5.2.7 on 2025-11-10 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animals'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='generic',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, verbose_name='属'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='pic2',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='animal_images/', verbose_name='画像2'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='pic3',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='animal_images/', verbose_name='画像3'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='pic4',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='animal_images/', verbose_name='画像4'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='pic5',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='animal_images/', verbose_name='画像5'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='scientific',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='学名'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='specific',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, verbose_name='種'),
        ),
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('zoo_id', models.AutoField(primary_key=True, serialize=False)),
                ('zoo_no', models.CharField(blank=True, max_length=32, unique=True, verbose_name='動物園No')),
                ('zoo_name', models.CharField(max_length=200, verbose_name='動物園名')),
                ('zoo_created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='登録日')),
                ('zoo_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日')),
            ],
            options={
                'verbose_name': 'Zoo',
                'verbose_name_plural': 'Zoos',
                'db_table': 'zoos',
                'indexes': [models.Index(fields=['zoo_no'], name='zoos_zoo_no_fdc486_idx')],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('pic_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.TextField(verbose_name='画像URL')),
                ('caption', models.TextField(blank=True, verbose_name='説明')),
                ('credit', models.CharField(blank=True, max_length=200, verbose_name='クレジット')),
                ('display_order', models.PositiveIntegerField(default=2, verbose_name='表示順')),
                ('is_primary', models.BooleanField(default=False, verbose_name='サムネにする')),
                ('pic_created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='登録日')),
                ('pic_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日')),
                ('animal', models.ForeignKey(db_column='animal_fk', on_delete=django.db.models.deletion.CASCADE, related_name='extra_pictures', to='animals.animal', verbose_name='動物')),
            ],
            options={
                'verbose_name': '追加画像（URL）',
                'verbose_name_plural': '追加画像（URL）',
                'db_table': 'pictures',
                'indexes': [models.Index(fields=['animal', 'display_order'], name='pictures_animal__de56be_idx'), models.Index(fields=['animal', 'is_primary'], name='pictures_animal__6caaf4_idx')],
                'constraints': [models.UniqueConstraint(fields=('animal', 'display_order'), name='uq_picture_order_per_animal')],
            },
        ),
    ]
