# Generated by Django 5.2.7 on 2025-10-28 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('zoo_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='動物園ID')),
                ('zoo_name', models.CharField(max_length=100, verbose_name='動物園名')),
            ],
            options={
                'verbose_name': '動物園',
                'verbose_name_plural': '動物園',
                'db_table': 'zoo',
            },
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='動物ID'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='txt',
            field=models.TextField(blank=True, verbose_name='説明文'),
        ),
        migrations.AddField(
            model_name='animal',
            name='zoo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='animals.zoo', verbose_name='所属動物園'),
        ),
    ]
