# Generated by Django 5.2.7 on 2025-11-12 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_options_alter_animal_generic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='zoo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='animals.zoo', verbose_name='所属動物園'),
        ),
        migrations.AddField(
            model_name='zoo',
            name='zoo_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='zoo',
            name='zoo_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号'),
        ),
    ]
