# Generated by Django 5.2.7 on 2025-10-28 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_zoo_alter_animal_animal_id_alter_animal_txt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZooSequence',
            fields=[
                ('zoo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seq', serialize=False, to='animals.zoo')),
                ('next_no', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'zoo_sequence',
            },
        ),
    ]
