# Generated by Django 5.2.7 on 2025-11-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animal_zoo_zoo_zoo_address_zoo_zoo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='zoo_postcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='郵便番号'),
        ),
    ]
