# Generated by Django 5.2.7 on 2025-11-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_zoo_zoo_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='diet',
            field=models.CharField(blank=True, choices=[('A', '肉食'), ('B', '草食'), ('C', '魚食'), ('D', '果実食'), ('E', '昆虫食')], max_length=1, null=True, verbose_name='主食'),
        ),
        migrations.AddField(
            model_name='animal',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='有効'),
        ),
    ]
