# Generated by Django 5.2.7 on 2025-11-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_animal_diet_animal_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='last_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最終支援日時'),
        ),
        migrations.AddField(
            model_name='zoo',
            name='last_paid_point_sum',
            field=models.PositiveIntegerField(default=0, verbose_name='最終支援時累計ポイント'),
        ),
    ]
