# Generated by Django 5.2.7 on 2025-11-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_zoo_last_paid_at_zoo_last_paid_point_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='last_paid_sub_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='サブスク最終支援日時'),
        ),
        migrations.AddField(
            model_name='zoo',
            name='last_paid_sub_total',
            field=models.PositiveIntegerField(default=0, verbose_name='サブスク最終支援累計額（円）'),
        ),
    ]
