# Generated by Django 5.2.7 on 2025-11-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_zoo_last_paid_sub_at_zoo_last_paid_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='sub_unpaid_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='未支援サブスク累計額（円）'),
        ),
    ]
