# Generated by Django 5.2.7 on 2025-10-29 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheerCoinPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField(verbose_name='購入チアコイン数')),
                ('price', models.PositiveIntegerField(verbose_name='購入金額（円）')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='購入日時')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheercoin_purchases', to=settings.AUTH_USER_MODEL, verbose_name='購入者')),
            ],
        ),
    ]
