# Generated by Django 5.2.7 on 2025-10-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='プラン')),
                ('plan_name', models.CharField(max_length=30, verbose_name='プラン名')),
                ('amount', models.PositiveIntegerField(verbose_name='金額')),
                ('st_point', models.PositiveIntegerField(default=0, verbose_name='スタポ')),
            ],
            options={
                'verbose_name': 'サブスクプラン',
                'verbose_name_plural': 'サブスクプラン',
                'db_table': 'subscribe',
                'indexes': [models.Index(fields=['code'], name='subscribe_code_342f47_idx')],
            },
        ),
    ]
