# Generated by Django 5.2.7 on 2025-10-27 02:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.BooleanField(default=True, verbose_name='継続')),
                ('sing_up', models.DateField(default=datetime.date.today, verbose_name='加入日')),
                ('end_day', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('sing_mon', models.PositiveIntegerField(default=0, verbose_name='合計加入月')),
                ('plan_name_snapshot', models.CharField(blank=True, max_length=30, verbose_name='契約時プラン名')),
                ('amount_snapshot', models.PositiveIntegerField(default=0, verbose_name='契約時金額')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_memberships', to=settings.AUTH_USER_MODEL, verbose_name='会員')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='subscription.subscribeplan', verbose_name='プラン')),
            ],
            options={
                'verbose_name': 'サブスク会員',
                'verbose_name_plural': 'サブスク会員',
                'db_table': 'sub_member',
                'indexes': [models.Index(fields=['member', 'plan'], name='sub_member_member__80478f_idx'), models.Index(fields=['sing_up'], name='sub_member_sing_up_457449_idx')],
            },
        ),
    ]
