# Generated by Django 5.2.7 on 2025-10-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_submember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submember',
            name='amount_snapshot',
        ),
        migrations.RemoveField(
            model_name='submember',
            name='id',
        ),
        migrations.RemoveField(
            model_name='submember',
            name='plan_name_snapshot',
        ),
        migrations.AddField(
            model_name='submember',
            name='sub_member_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
