# Generated by Django 5.2.7 on 2025-11-12 03:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_options_alter_animal_generic_and_more'),
        ('subscription', '0003_remove_submember_amount_snapshot_remove_submember_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='submember',
            name='sub_member_sing_up_457449_idx',
        ),
        migrations.AlterField(
            model_name='submember',
            name='sub',
            field=models.BooleanField(db_column='sub', default=True, verbose_name='継続'),
        ),
        migrations.RenameField(
            model_name='submember',
            old_name='sub',
            new_name='is_recurring',
        ),
        migrations.AlterField(
            model_name='submember',
            name='sing_mon',
            field=models.PositiveIntegerField(db_column='sing_mon', default=0, verbose_name='合計加入月'),
        ),
        migrations.RenameField(
            model_name='submember',
            old_name='sing_mon',
            new_name='sign_mon',
        ),
        migrations.AlterField(
            model_name='submember',
            name='sing_up',
            field=models.DateField(db_column='sing_up', default=datetime.date.today, verbose_name='加入日'),
        ),
        migrations.RenameField(
            model_name='submember',
            old_name='sing_up',
            new_name='sign_up',
        ),
        migrations.AddField(
            model_name='submember',
            name='animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='animals.animal', verbose_name='サポート動物'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='会員'),
        ),
        migrations.AddIndex(
            model_name='submember',
            index=models.Index(fields=['sign_up'], name='sub_member_sing_up_457449_idx'),
        ),
        migrations.AddIndex(
            model_name='submember',
            index=models.Index(fields=['member', 'animal'], name='sub_member_member__f80ae9_idx'),
        ),
    ]
