# Generated by Django 5.2.7 on 2025-11-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_remove_submember_sub_member_sing_up_457449_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submember',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効プラン'),
        ),
    ]
