# Generated by Django 5.2.7 on 2025-10-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="birth",
            field=models.DateField(blank=True, null=True, verbose_name="生年月日"),
        ),
    ]
