# Generated by Django 5.2.7 on 2025-11-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_member_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_keeper',
            field=models.BooleanField(default=False, verbose_name='飼育員'),
        ),
    ]
