# Generated by Django 5.2.7 on 2025-11-11 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_member_is_keeper'),
        ('animals', '0002_alter_animal_options_alter_animal_generic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='zoo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.zoo', verbose_name='所属動物園'),
        ),
    ]
