# Generated by Django 5.2.7 on 2025-10-24 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goods_detail_images/', verbose_name='詳細画像')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_images', to='goods.goods')),
            ],
        ),
    ]
