# Generated by Django 5.2.7 on 2025-10-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goodsimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='名無し', verbose_name='住所'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=0, max_length=20, verbose_name='電話番号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='未登録', max_length=20, verbose_name='郵便番号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(default='0000000000', max_length=100, verbose_name='名前'),
            preserve_default=False,
        ),
    ]
