# Generated by Django 5.2.7 on 2025-11-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_remove_order_shipping_address_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '未発送'), ('shipped', '発送済み')], default='pending', max_length=10, verbose_name='発送状況'),
        ),
    ]
