# Generated by Django 5.2.7 on 2025-11-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '未発送'), ('shipped', '発送済み'), ('cancelled', 'キャンセル')], default='pending', max_length=10, verbose_name='発送状況'),
        ),
    ]
