# Generated by Django 5.2.7 on 2026-01-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '未発送'), ('shipped', '発送済み'), ('cancelled', 'キャンセル済み')], default='pending', max_length=10, verbose_name='発送状況'),
        ),
    ]
